In [4]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [5]:
df = pd.read_csv('iris.csv')
# # Import necessary libraries
# from sklearn.datasets import load_iris
# import pandas as pd

# # Load the Iris dataset
# iris = load_iris()
# X = pd.DataFrame(iris.data, columns=iris.feature_names)  # Features
# y = pd.Series(iris.target)  # Target labels

# print(X.head())  # Display the first few rows of the dataset
# print(y.head())  # Display the first few target values


In [16]:
df.Species.nunique()

3

Define features and target variable

In [7]:
X = df.drop('Species', axis=1)  # Features
y = df['Species']  # Target variable

Split data into training and testing sets

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


Create Decision Tree classifier and train it

In [18]:
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier()

Make predictions on the test set

In [19]:
y_pred = dt_classifier.predict(X_test)

In [20]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the results
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 1.0
Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
